//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTop10word", ReplyAction="http://tempuri.org/IService1/getTop10wordResponse")]
        string getTop10word(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTop10word", ReplyAction="http://tempuri.org/IService1/getTop10wordResponse")]
        System.Threading.Tasks.Task<string> getTop10wordAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wordfiter", ReplyAction="http://tempuri.org/IService1/wordfiterResponse")]
        string wordfiter(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wordfiter", ReplyAction="http://tempuri.org/IService1/wordfiterResponse")]
        System.Threading.Tasks.Task<string> wordfiterAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/print", ReplyAction="http://tempuri.org/IService1/printResponse")]
        string print(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/print", ReplyAction="http://tempuri.org/IService1/printResponse")]
        System.Threading.Tasks.Task<string> printAsync(string number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference2.IService1>, WebApplication1.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getTop10word(string url) {
            return base.Channel.getTop10word(url);
        }
        
        public System.Threading.Tasks.Task<string> getTop10wordAsync(string url) {
            return base.Channel.getTop10wordAsync(url);
        }
        
        public string wordfiter(string str) {
            return base.Channel.wordfiter(str);
        }
        
        public System.Threading.Tasks.Task<string> wordfiterAsync(string str) {
            return base.Channel.wordfiterAsync(str);
        }
        
        public string print(string number) {
            return base.Channel.print(number);
        }
        
        public System.Threading.Tasks.Task<string> printAsync(string number) {
            return base.Channel.printAsync(number);
        }
    }
}
